@host=http://localhost:5053

POST {{host}}/CSV
Content-Type: application/json
{
  "name": "TestName10",
  "birthDate": "1989-01-01T00:00:00Z",
  "isMarried": true,
  "phone": "1234567859",
  "salary": 5000.00
}