@host=http://localhost:5053

POST {{host}}/CSV
Content-Type: application/json
{
  "name": "IIIIIIIIIII",
  "birthDate": "1956-01-01T00:00:00Z",
  "isMarried": true,
  "phone": "1234567859",
  "salary": 700.00
}