@host=http://localhost:5053

Put {{host}}/CSV
Content-Type: application/json
{
    "id": "5f2e5e00-64b4-4912-b065-22829f219bbb",
    "name": "TestName10101010",
    "birthDate": "1989-01-01T00:00:00",
    "isMarried": true,
    "phone": "12334344567890",
    "salary": 5000.00
}