@host=http://localhost:5053

Put {{host}}/CSV
Content-Type: application/json
{
    "id": "9c4829f3-8c3f-497a-b98e-412f72cccab8",
    "name": "Stanislav Severin",
    "birthDate": "1980-01-01T00:00:00",
    "isMarried": true,
    "phone": "1234562323789",
    "salary": 100.00
}